<?xml version="1.0" encoding="UTF-8"?>
<robot name="EDUMIP" version="2" xmlns:xacro="http://www.ros.org/wiki/xacro" xmlns:ros="http://www.ros.org/wiki/ros2">

	 
	<xacro:property name="wheel_width" value="0.010" />
	<xacro:property name="body_height" value="0.1" />
	<xacro:property name="body_width" value="0.050" />
	<xacro:property name="body_length" value="0.035" />
	<xacro:property name="PI" value="3.1415926535897931"/>
	<xacro:property name="wheel_separation" value="0.070" />
  	<xacro:property name="wheel_radius" value="0.034" />

	<xacro:include filename="$(find edumip_description)/urdf/gazebo.xacro" />
	<xacro:balance left_joint="left_wheel_joint" right_joint="right_wheel_joint" wheel_separation="${wheel_separation}" wheel_radius="${wheel_radius}">
    </xacro:balance>

	<!-- Wheel xacro -->
	<xacro:macro name="wheel" params="prefix width radius *origin">

		<link name="${prefix}_wheel" >

			<visual>
				<origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
				<geometry>
					<cylinder length="${width}" radius="${radius}"/>
				</geometry>
				<material name="White">
		        	<color rgba="0.8 0.8 0.8 0.3"/>
		        </material>
			</visual>

			<collision>
				<origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
				<geometry>
					<cylinder length="${width}" radius="${radius}"/>
				</geometry>
			</collision>

			<inertial>
				<origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
				<mass value="0.030"/>
				<inertia ixx="1.75e-5" ixy="0" ixz="0" iyy="1.75e-5" iyz="0" izz="1.75e-5"/>
			</inertial>

		</link>

		<joint name="${prefix}_wheel_joint" type="continuous">
		    <parent link="base_link"/>
		    <child link="${prefix}_wheel"/>
		    <xacro:insert_block name="origin" /> 
		    <axis xyz="0 1 0"/>
	  	</joint>

	  	<gazebo>
		  	<plugin
			    filename="libignition-gazebo-joint-state-publisher-system"
			    name="ignition::gazebo::systems::JointStatePublisher"/>
		</gazebo>

	</xacro:macro>

	<xacro:macro name="edumip">
		<link name="base_link">

			<visual>
				<origin xyz="0 0 ${0.5*body_height}" rpy="0 -0.20 0"/>
				<geometry>
					<box size="${body_length} ${body_width} ${body_height}"/>
				</geometry>
				<material name="Blue">
					<color rgba="0 0.0 1.0 0.5"/>
				</material>
			</visual>

			<collision>
				<origin xyz="0 0 ${0.5*body_height}" rpy="0 -0.20 0"/>
				<geometry>
					<box size="${body_length} ${body_width} ${body_height}"/>
				</geometry>
			</collision>

			<inertial>
				<origin xyz="0 0 ${0.5*body_height}" rpy="0 0 0"/>
				<mass value="0.180"/>
				<inertia ixx="6.0e-4" ixy="0" ixz="0" iyy="6.0e-4" iyz="0" izz="6.0e-4"/>
			</inertial>

		</link>

		<xacro:wheel prefix="left" width="${wheel_width}" radius="${wheel_radius}">
			<origin xyz="0 ${0.5*wheel_separation} 0" rpy="0 0 0"/>
		</xacro:wheel>

		<xacro:wheel prefix="right" width="${wheel_width}" radius="${wheel_radius}">
			<origin xyz="0 -${0.5*wheel_separation} 0" rpy="0 0 0"/>
		</xacro:wheel>

		<gazebo>
			<plugin filename="tot_plugin" name="ignition::gazebo::systems::TotPlugin">
				<sensor1> towerA </sensor1>
				<sensor2> towerB </sensor2>
			</plugin>
		</gazebo>

	</xacro:macro>

</robot>